In [2]:
import pandas as pd
df=pd.read_csv("modified_data.csv")
print(df)

            date       price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0     2014-05-02   313000.00       3.0       1.50         1340      7912
1     2014-05-02  2384000.00       5.0       2.50         3650      9050
2     2014-05-02   342000.00       3.0       2.00         1930     11947
3     2014-05-02   420000.00       3.0       2.25         2000      8030
4     2014-05-02   550000.00       4.0       2.50         1940     10500
...          ...         ...       ...        ...          ...       ...
4595  2014-07-09   308166.67       3.0       1.75         1510      6360
4596  2014-07-09   534333.33       3.0       2.50         1460      7573
4597  2014-07-09   416904.17       3.0       2.50         3010      7014
4598  2014-07-10   203400.00       4.0       2.00         2090      6630
4599  2014-07-10   220600.00       3.0       2.50         1490      8102

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5           0     0          3        1340              0
1        2.0           0     4          5        3370            280
2        1.0           0     0          4        1930              0
3        1.0           0     0          4        1000           1000
4        1.0           0     0          4        1140            800
...      ...         ...   ...        ...         ...            ...
4595     1.0           0     0          4        1510              0
4596     2.0           0     0          3        1460              0
4597     2.0           0     0          3        3010              0
4598     1.0           0     0          3        1070           1020
4599     2.0           0     0          4        1490              0

      yr_built  yr_renovated                    street       city  statezip  \
0         1955          2005      18810 Densmore Ave N  Shoreline  WA 98133
1         1921             0           709 W Blaine St    Seattle  WA 98119
2         1966             0  26206-26214 143rd Ave SE       Kent  WA 98042
3         1963             0           857 170th Pl NE   Bellevue  WA 98008
4         1976          1992         9105 170th Ave NE    Redmond  WA 98052
...        ...           ...                       ...        ...       ...
4595      1954          1979            501 N 143rd St    Seattle  WA 98133
4596      1983          2009          14855 SE 10th Pl   Bellevue  WA 98007
4597      2009             0          759 Ilwaco Pl NE     Renton  WA 98059
4598      1974             0         5148 S Creston St    Seattle  WA 98178
4599      1990             0         18717 SE 258th St  Covington  WA 98042

      price_per_sqft
0             233.58
1             653.15
2             177.20
3             210.00
4             283.51
...              ...
4595          204.08
4596          365.98
4597          138.51
4598           97.32
4599          148.05

[4600 rows x 18 columns]

In [3]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,price_per_sqft
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261,265.876209
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536,357.503362
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000,180.817500
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000,243.855000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000,314.840000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000,22533.900000

In [10]:
df1 = df.groupby('price')['sqft_living'].max()
print(df1)

price
0.0            8020
7800.0          780
80000.0         430
83000.0         900
83300.0        1490
              ...
4489000.0      6430
4668000.0      9640
7062500.0     10040
12899000.0     2190
26590000.0     1180
Name: sqft_living, Length: 1741, dtype: int64

In [6]:
row = df.loc[df["price"].idxmax()]
print("floors:", row["floors"])
print("sqft_living:", row["sqft_living"])

floors: 1.0
sqft_living: 1180

In [7]:
max_index = df["price"].idxmin()
print(max_index)

4354

In [8]:
df_sorted=df.sort_values(by="price",ascending=True)
print("sorted by price:\n",df_sorted,"\n")

sorted by price:
             date       price  bedrooms  bathrooms  sqft_living  sqft_lot  \
4567  2014-07-02         0.0       4.0       2.50         4080     18362
4405  2014-05-20         0.0       4.0       3.75         3300      4545
4408  2014-05-21         0.0       5.0       2.25         2880     11965
4411  2014-05-22         0.0       5.0       2.25         2000      7900
4499  2014-06-17         0.0       5.0       3.75         3870      8225
...          ...         ...       ...        ...          ...       ...
2761  2014-06-18   4489000.0       4.0       3.00         6430     27517
2654  2014-06-17   4668000.0       5.0       6.75         9640     13068
2286  2014-06-11   7062500.0       5.0       4.50        10040     37325
4346  2014-06-23  12899000.0       3.0       2.50         2190     11394
4350  2014-07-03  26590000.0       3.0       2.00         1180      7793

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
4567     2.0           0     2          4        4080              0
4405     1.5           0     4          3        2600            700
4408     2.0           0     0          4        2880              0
4411     1.0           0     0          4        1300            700
4499     2.0           0     0          3        3870              0
...      ...         ...   ...        ...         ...            ...
2761     2.0           0     0          3        6430              0
2654     1.0           1     4          3        4820           4820
2286     2.0           1     2          3        7680           2360
4346     1.0           0     0          3        1550            640
4350     1.0           0     0          4        1180              0

      yr_built  yr_renovated                 street           city  statezip  \
4567      1983             0       2710 95th Ave NE     Clyde Hill  WA 98004
4405      1926          1999       3665 50th Ave NE        Seattle  WA 98105
4408      1990             0      25437 163rd Pl SE      Covington  WA 98042
4411      1986             0        3202 S 194th St         SeaTac  WA 98188
4499      1998          2006   101-127 247th Ave SE      Sammamish  WA 98074
...        ...           ...                    ...            ...       ...
2761      2001             0  1149-1199 91st Ave NE       Bellevue  WA 98004
2654      1983          2009    5044 Butterworth Rd  Mercer Island  WA 98040
2286      1940          2001       4442 95th Ave NE       Bellevue  WA 98004
4346      1956          2001        5426 40th Ave W        Seattle  WA 98199
4350      1992             0      12005 SE 219th Ct           Kent  WA 98031

      price_per_sqft
4567            0.00
4405            0.00
4408            0.00
4411            0.00
4499            0.00
...              ...
2761          698.13
2654          484.23
2286          703.44
4346         5889.95
4350        22533.90

[4600 rows x 18 columns]

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4600 non-null   object
 1   price           4600 non-null   float64
 2   bedrooms        4600 non-null   float64
 3   bathrooms       4600 non-null   float64
 4   sqft_living     4600 non-null   int64
 5   sqft_lot        4600 non-null   int64
 6   floors          4600 non-null   float64
 7   waterfront      4600 non-null   int64
 8   view            4600 non-null   int64
 9   condition       4600 non-null   int64
 10  sqft_above      4600 non-null   int64
 11  sqft_basement   4600 non-null   int64
 12  yr_built        4600 non-null   int64
 13  yr_renovated    4600 non-null   int64
 14  street          4600 non-null   object
 15  city            4600 non-null   object
 16  statezip        4600 non-null   object
 17  price_per_sqft  4600 non-null   float64
dtypes: float64(5), int64(9), object(4)
memory usage: 647.0+ KB
None

In [11]:
print(df.groupby("floors")["sqft_above"].mean())

floors
1.0    1336.515639
1.5    1658.677928
2.0    2440.383766
2.5    2813.902439
3.0    1750.109375
3.5    2232.000000
Name: sqft_above, dtype: float64

In [12]:
most_valued=df.loc[df["price"].idxmax()]
print(most_valued)

date                     2014-07-03
price                    26590000.0
bedrooms                        3.0
bathrooms                       2.0
sqft_living                    1180
sqft_lot                       7793
floors                          1.0
waterfront                        0
view                              0
condition                         4
sqft_above                     1180
sqft_basement                     0
yr_built                       1992
yr_renovated                      0
street            12005 SE 219th Ct
city                           Kent
statezip                   WA 98031
price_per_sqft              22533.9
Name: 4350, dtype: object

In [13]:
df1=df.dropna()
df1

df2=df.dropna(axis=1)
print(df2)
 
df3=df.fillna(0)
print(df3)
 
df3=df.bfill()
df3
 
df3=df.ffill()
df3

            date       price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0     2014-05-02   313000.00       3.0       1.50         1340      7912
1     2014-05-02  2384000.00       5.0       2.50         3650      9050
2     2014-05-02   342000.00       3.0       2.00         1930     11947
3     2014-05-02   420000.00       3.0       2.25         2000      8030
4     2014-05-02   550000.00       4.0       2.50         1940     10500
...          ...         ...       ...        ...          ...       ...
4595  2014-07-09   308166.67       3.0       1.75         1510      6360
4596  2014-07-09   534333.33       3.0       2.50         1460      7573
4597  2014-07-09   416904.17       3.0       2.50         3010      7014
4598  2014-07-10   203400.00       4.0       2.00         2090      6630
4599  2014-07-10   220600.00       3.0       2.50         1490      8102

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5           0     0          3        1340              0
1        2.0           0     4          5        3370            280
2        1.0           0     0          4        1930              0
3        1.0           0     0          4        1000           1000
4        1.0           0     0          4        1140            800
...      ...         ...   ...        ...         ...            ...
4595     1.0           0     0          4        1510              0
4596     2.0           0     0          3        1460              0
4597     2.0           0     0          3        3010              0
4598     1.0           0     0          3        1070           1020
4599     2.0           0     0          4        1490              0

      yr_built  yr_renovated                    street       city  statezip  \
0         1955          2005      18810 Densmore Ave N  Shoreline  WA 98133
1         1921             0           709 W Blaine St    Seattle  WA 98119
2         1966             0  26206-26214 143rd Ave SE       Kent  WA 98042
3         1963             0           857 170th Pl NE   Bellevue  WA 98008
4         1976          1992         9105 170th Ave NE    Redmond  WA 98052
...        ...           ...                       ...        ...       ...
4595      1954          1979            501 N 143rd St    Seattle  WA 98133
4596      1983          2009          14855 SE 10th Pl   Bellevue  WA 98007
4597      2009             0          759 Ilwaco Pl NE     Renton  WA 98059
4598      1974             0         5148 S Creston St    Seattle  WA 98178
4599      1990             0         18717 SE 258th St  Covington  WA 98042

      price_per_sqft
0             233.58
1             653.15
2             177.20
3             210.00
4             283.51
...              ...
4595          204.08
4596          365.98
4597          138.51
4598           97.32
4599          148.05

[4600 rows x 18 columns]
            date       price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0     2014-05-02   313000.00       3.0       1.50         1340      7912
1     2014-05-02  2384000.00       5.0       2.50         3650      9050
2     2014-05-02   342000.00       3.0       2.00         1930     11947
3     2014-05-02   420000.00       3.0       2.25         2000      8030
4     2014-05-02   550000.00       4.0       2.50         1940     10500
...          ...         ...       ...        ...          ...       ...
4595  2014-07-09   308166.67       3.0       1.75         1510      6360
4596  2014-07-09   534333.33       3.0       2.50         1460      7573
4597  2014-07-09   416904.17       3.0       2.50         3010      7014
4598  2014-07-10   203400.00       4.0       2.00         2090      6630
4599  2014-07-10   220600.00       3.0       2.50         1490      8102

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5           0     0          3        1340              0
1        2.0           0     4          5        3370            280
2        1.0           0     0          4        1930              0
3        1.0           0     0          4        1000           1000
4        1.0           0     0          4        1140            800
...      ...         ...   ...        ...         ...            ...
4595     1.0           0     0          4        1510              0
4596     2.0           0     0          3        1460              0
4597     2.0           0     0          3        3010              0
4598     1.0           0     0          3        1070           1020
4599     2.0           0     0          4        1490              0

      yr_built  yr_renovated                    street       city  statezip  \
0         1955          2005      18810 Densmore Ave N  Shoreline  WA 98133
1         1921             0           709 W Blaine St    Seattle  WA 98119
2         1966             0  26206-26214 143rd Ave SE       Kent  WA 98042
3         1963             0           857 170th Pl NE   Bellevue  WA 98008
4         1976          1992         9105 170th Ave NE    Redmond  WA 98052
...        ...           ...                       ...        ...       ...
4595      1954          1979            501 N 143rd St    Seattle  WA 98133
4596      1983          2009          14855 SE 10th Pl   Bellevue  WA 98007
4597      2009             0          759 Ilwaco Pl NE     Renton  WA 98059
4598      1974             0         5148 S Creston St    Seattle  WA 98178
4599      1990             0         18717 SE 258th St  Covington  WA 98042

      price_per_sqft
0             233.58
1             653.15
2             177.20
3             210.00
4             283.51
...              ...
4595          204.08
4596          365.98
4597          138.51
4598           97.32
4599          148.05

[4600 rows x 18 columns]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
0,2014-05-02,313000.00,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,233.58
1,2014-05-02,2384000.00,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,653.15
2,2014-05-02,342000.00,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,177.20
3,2014-05-02,420000.00,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,210.00
4,2014-05-02,550000.00,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,283.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09,308166.67,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,204.08
4596,2014-07-09,534333.33,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,365.98
4597,2014-07-09,416904.17,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,138.51
4598,2014-07-10,203400.00,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,97.32
4599,2014-07-10,220600.00,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,148.05

In [15]:
print(df["price"].dtype)

float64

In [18]:
result = df[df["city"].str.startswith("Auburn")]
print(result)

            date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
17    2014-05-02  367500.00       4.0       3.00         3110      7231
34    2014-05-02  400000.00       4.0       2.50         3630     42884
56    2014-05-02  491500.00       4.0       1.75         2190    125452
70    2014-05-04  331950.00       4.0       2.50         2530      9933
103   2014-05-05  328000.00       4.0       2.50         2370      6500
...          ...        ...       ...        ...          ...       ...
4425  2014-05-28   87500.00       2.0       1.00          780      6685
4463  2014-06-05  237227.86       4.0       2.50         2068      7242
4518  2014-06-20  248400.00       3.0       1.75         1880     11249
4520  2014-06-20       0.00       4.0       2.50         1960     11600
4593  2014-07-08  289373.31       3.0       2.50         2538      4600

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
17       2.0           0     0          3        3110              0
34       1.5           0     0          3        2300           1330
56       1.0           0     2          3        2190              0
70       2.0           0     2          3        2010            520
103      2.0           0     0          3        2370              0
...      ...         ...   ...        ...         ...            ...
4425     1.0           0     0          4         780              0
4463     2.0           0     0          4        2068              0
4518     1.0           0     0          3        1330            550
4520     1.0           0     0          5         980            980
4593     2.0           0     0          3        2538              0

      yr_built  yr_renovated                    street    city  statezip  \
17        1997             0         11224 SE 306th Pl  Auburn  WA 98092
34        1979          2014  5172-5198 Heather Ave SE  Auburn  WA 98092
56        1968          1997        36850 204th Ave SE  Auburn  WA 98092
70        1990          2009               925 48th Ct  Auburn  WA 98092
103       1998          2006        12621 SE 300th Way  Auburn  WA 98092
...        ...           ...                       ...     ...       ...
4425      1948             0               311 L St SE  Auburn  WA 98002
4463      1976          1992     30036-30116 42nd Pl S  Auburn  WA 98001
4518      1985             0              2431 T St NW  Auburn  WA 98001
4520      1931             0            506 21st St SE  Auburn  WA 98002
4593      2013          1923     5703 Charlotte Ave SE  Auburn  WA 98092

      price_per_sqft
17            118.17
34            110.19
56            224.43
70            131.21
103           138.40
...              ...
4425          112.18
4463          114.71
4518          132.13
4520            0.00
4593          114.02

[176 rows x 18 columns]

In [19]:
result = df["city"].str.replace(r'[^a-zA-Z0-9]','',regex=True)
print(result)

0       Shoreline
1         Seattle
2            Kent
3        Bellevue
4         Redmond
          ...
4595      Seattle
4596     Bellevue
4597       Renton
4598      Seattle
4599    Covington
Name: city, Length: 4600, dtype: object

In [24]:
result = df[df["waterfront"] == 1]
print(result)

            date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
381   2014-05-08   988500.0       3.0       2.75         2015     16807
404   2014-05-09  2400000.0       3.0       2.25         3000     11665
478   2014-05-12  1200000.0       3.0       1.75         1560      8078
518   2014-05-12   947500.0       3.0       2.75         2980     27144
535   2014-05-12   615000.0       2.0       1.75         2040     28593
581   2014-05-13  2555000.0       4.0       2.50         5300     26211
1163  2014-05-22   503000.0       2.0       1.75         2860     59612
1301  2014-05-24  2000000.0       5.0       4.00         4580      4443
1464  2014-05-28  1175000.0       3.0       2.50         1970     23180
1639  2014-05-30   800000.0       2.0       2.25         1730     31491
2031  2014-06-06  1150000.0       3.0       1.50         2170     16600
2083  2014-06-08  2700000.0       4.0       3.25         4420      7850
2286  2014-06-11  7062500.0       5.0       4.50        10040     37325
2411  2014-06-12   835000.0       3.0       3.00         2790     12523
2608  2014-06-16   385000.0       2.0       1.00          830     26329
2654  2014-06-17  4668000.0       5.0       6.75         9640     13068
2690  2014-06-17   465000.0       2.0       2.00         1494     19271
2772  2014-06-18  3000000.0       4.0       4.25         4850     12445
2846  2014-06-19  2200000.0       5.0       4.75         5990     10450
2964  2014-06-20   950000.0       3.0       3.25         3050     18892
3153  2014-06-23  1700000.0       3.0       2.75         2810     18731
3195  2014-06-24   549000.0       2.0       1.00         2034     13392
3283  2014-06-25   995000.0       3.0       4.50         4380     47044
3429  2014-06-26   663000.0       3.0       2.50         2480     37843
3584  2014-06-27   528000.0       2.0       0.75          840     40642
3682  2014-06-30  1309500.0       4.0       2.50         2680     12215
3791  2014-07-01  2367000.0       3.0       2.25         3530     17450
3950  2014-07-03   975000.0       6.0       2.75         2520     54160
4142  2014-07-08  1675000.0       3.0       2.50         3490      8343
4523  2014-06-23        0.0       3.0       4.50         5230     17826
4528  2014-06-24        0.0       4.0       5.00         4550     18641
4529  2014-06-24   542500.0       5.0       2.75         3831     13800
4588  2014-07-08        0.0       4.0       2.25         2890     18226

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
381      2.0           1     4          3        2015              0
404      1.5           1     4          3        3000              0
478      1.5           1     4          4        1560              0
518      1.5           1     2          5        2180            800
535      1.5           1     3          4        2040              0
581      2.0           1     2          2        4570            730
1163     1.0           1     4          3        1510           1350
1301     3.0           1     4          3        4580              0
1464     1.0           1     4          3        1100            870
1639     2.0           1     2          4        1730              0
2031     1.0           1     2          3        1130           1040
2083     2.0           1     4          3        3150           1270
2286     2.0           1     2          3        7680           2360
2411     2.0           1     4          4        1600           1190
2608     1.0           1     3          4         830              0
2654     1.0           1     4          3        4820           4820
2690     2.0           1     4          3        1494              0
2772     2.0           1     4          5        3850           1000
2846     2.0           1     4          3        4050           1940
2964     1.0           1     4          4        1650           1400
3153     2.0           1     4          4        2810              0
3195     1.0           1     4          5        1159            875
3283     2.0           1     3          3        3720            660
3429     1.5           1     3          4        2480              0
3584     1.0           1     4          4         840              0
3682     1.0           1     4          3        1590           1090
3791     1.0           1     3          3        1840           1690
3950     2.0           1     4          3        2520              0
4142     2.0           1     4          4        2150           1340
4523     2.0           1     4          3        3740           1490
4528     1.0           1     4          3        2600           1950
4529     2.0           1     4          3        3831              0
4588     3.0           1     4          3        2890              0

      yr_built  yr_renovated                             street  \
381       2007             0              2973-3563 SW 172nd St
404       2001             0          East Lake Sammamish Trail
478       1928             0                  3603 W Mercer Way
518       1917             0                       Indian Trail
535       1919          1990                23014 Vashon Hwy SW
581       1923             0                   4437 55th Ave NE
1163      1948          2003                   4338 SW 307th St
1301      2004          2003  4277 E Lake Sammamish Shore Ln SE
1464      1937          1998                   5923 Beach Dr SW
1639      1947          1988                   10060 SW Dock St
2031      1979          2014   2244 West Lake Sammamish Pkwy NE
2083      2001             0                   17834 SE 40th Pl
2286      1940          2001                   4442 95th Ave NE
2411      1977             0                    27231 8th Ave S
2608      1928             0              7310 SW Maury Park Rd
2654      1983          2009                5044 Butterworth Rd
2690      1943          1997                  12533 SW 148th St
2772      1989             0        11031 Champagne Point Rd NE
2846      2002             0               5170 NW Sammamish Rd
2964      1962             0                 554-598 S 239th St
3153      1974             0   2860 West Lake Sammamish Pkwy NE
3195      1947             0               13013 SW Bachelor Rd
3283      1968          1990                  14423 25th Ave SW
3429      1974             0              7030 SW Maury Park Rd
3584      1937             0           8907 SW Quartermaster Dr
3682      1956          2001          18051 Normandy Terrace SW
3791      1930          1993                  7436 E Mercer Way
3950      1954          2005                   3405 SW Seola Ln
4142      1939          1991                 Burke-Gilman Trail
4523      2005             0                  7455 W Mercer Way
4528      2002             0       425 E Lake Sammamish Pkwy SE
4529      1959          1980                    6208 SE 22nd St
4588      1984             0      3227-3399 Mountain View Ave N

               city  statezip  price_per_sqft
381          Burien  WA 98166          490.57
404       Sammamish  WA 98075          800.00
478   Mercer Island  WA 98040          769.23
518          Burien  WA 98166          317.95
535          Vashon  WA 98070          301.47
581         Seattle  WA 98105          482.08
1163    Federal Way  WA 98023          175.87
1301      Sammamish  WA 98075          436.68
1464        Seattle  WA 98136          596.45
1639         Vashon  WA 98070          462.43
2031        Redmond  WA 98052          529.95
2083       Bellevue  WA 98008          610.86
2286       Bellevue  WA 98004          703.44
2411     Des Moines  WA 98198          299.28
2608         Vashon  WA 98070          463.86
2654  Mercer Island  WA 98040          484.23
2690         Vashon  WA 98070          311.24
2772       Kirkland  WA 98034          618.56
2846       Issaquah  WA 98027          367.28
2964     Des Moines  WA 98198          311.48
3153        Redmond  WA 98052          604.98
3195         Vashon  WA 98070          269.91
3283         Burien  WA 98166          227.17
3429         Vashon  WA 98070          267.34
3584         Vashon  WA 98070          628.57
3682  Normandy Park  WA 98166          488.62
3791  Mercer Island  WA 98040          670.54
3950        Seattle  WA 98146          386.90
4142        Seattle  WA 98125          479.94
4523  Mercer Island  WA 98040            0.00
4528      Sammamish  WA 98074            0.00
4529  Mercer Island  WA 98040          141.61
4588         Renton  WA 98056            0.00

In [28]:


df["Years_Difference"] = df["yr_renovated"] - df["yr_built"]
2
print(df[["yr_built", "yr_renovated", "Years_Difference"]])

      yr_built  yr_renovated  Years_Difference
0         1955          2005                50
1         1921             0             -1921
2         1966             0             -1966
3         1963             0             -1963
4         1976          1992                16
...        ...           ...               ...
4595      1954          1979                25
4596      1983          2009                26
4597      2009             0             -2009
4598      1974             0             -1974
4599      1990             0             -1990

[4600 rows x 3 columns]